import Head from 'next/head'
import Image from 'next/image'
import { Hero,  ServicesIntro, Brand, Features } from '@sections'
import Offres from '../sections/offres'
import About from '../sections/about'
import Contact from '../components/footer'








export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
     <Hero/>
     <Brand/>
     <ServicesIntro/>
     <Features/>
     <Offres/>
     <About/>
     <Contact/>
     
  

    </>
  )
}
